# Versions
mod_version=2.0.5
minecraft_version=26.3

# Common Dependencies
YACL_version=3.9.6+26.3-fabric
raised_version=Fabric-26.2-5.1.2
farmers_delight_version=26.3-3.6.24

# Done to increase the memory available to gradle.
org.gradle.jvmargs=-Xmx1G
org.gradle.parallel=true

# IntelliJ IDEA is not yet fully compatible with configuration cache, see: https://github.com/FabricMC/fabric-loom/issues/1349
org.gradle.configuration-cache=false

# Fabric Properties
# check these on https://fabricmc.net/develop
loader_version=0.19.5
loom_version=1.17-SNAPSHOT

# Mod Properties
maven_group=antigers.melancholic_hunger
archives_base_name=melancholic_hunger

# Fabric Specific Dependencies
fabric_api_version=0.160.5+26.3
mod_menu_version=21.0.0-beta.1