# Done to increase the memory available to gradle.
org.gradle.jvmargs=-Xmx1G
org.gradle.parallel=true

# IntelliJ IDEA is not yet fully compatible with configuration cache, see: https://github.com/FabricMC/fabric-loom/issues/1349
org.gradle.configuration-cache=false

# Fabric Properties
# check these on https://fabricmc.net/develop
minecraft_version=26.3-pre-3
loader_version=0.19.5
loom_version=1.17-SNAPSHOT

# Mod Properties
mod_version=2.0.4
maven_group=antigers.melancholic_hunger
archives_base_name=melancholic_hunger

# Dependencies
fabric_api_version=0.160.2+26.3
YACL_version=3.9.6+26.3-fabric
mod_menu_version=21.0.0-alpha.1
#architectury_version=13.0.8
#nostalgic_tweaks_version=2.0.0-beta.904
raised_version=Fabric-26.1.1-5.1.2
manningham_mills_version=v2.3
farmers_delight_version=26.2-3.6.6